// Generated by arsxml2wv from node 8 (완료 메뉴). Review before use.
var sWorkTime = app.worktime;
var sWTType = "B";
if (sWorkTime == "Y")
{
	sWTType = "A";
}

var wvMsgType = "WV2000Q";
var wvMenu = "";

wvMenu += "S\$SHKE00;";
wvMenu += "BTH\$0\$OFF;";
wvMenu += "BTH\$1\$ON;";
wvMenu += "TIT\$0\$테스트 이체;";
wvMenu += "TXT\$0\$C\$원하시는 메뉴를 선택해 주세요.;";
wvMenu += "BTN\$0\$다른 이체\$1;";
wvMenu += "BTN\$1\$처음으로\$9;";
wvMenu += "BTN\$2\$이전 단계\$#;";
wvMenu += "CHA\$0\$" + app.wvChat + ";";
wvMenu += "BOT\$0\$" + sWTType + ";";

app.wvMsgType = wvMsgType;
app.wvMenu = wvMenu;
app.wvReadTimeout = "A";
app.wvMaxRetryCount = "2";	// 최대 화면 팝업 횟수
