// Generated by arsxml2wv from node 3 (금액 입력). Review before use.
var sWorkTime = app.worktime;
var sWTType = "B";
if (sWorkTime == "Y")
{
	sWTType = "A";
}

var wvMsgType = "WV2000Q";
var wvMenu = "";

wvMenu += "S\$SHKC21;";
wvMenu += "BTH\$0\$ON;";
wvMenu += "BTH\$1\$ON;";
wvMenu += "TIT\$0\$테스트 이체;";
wvMenu += "TXT\$0\$C\$이체 금액과 우물정자를 눌러 주십시오.;";
wvMenu += "INPH\$0\$1\$12\$금액 입력\$N\$ON;";
wvMenu += "INBTN\$0\$확인;";
wvMenu += "CHA\$0\$" + app.wvChat + ";";
wvMenu += "BOT\$0\$" + sWTType + ";";

app.wvMsgType = wvMsgType;
app.wvMenu = wvMenu;
app.wvReadTimeout = "B";
app.wvMaxRetryCount = "2";	// 최대 화면 팝업 횟수
