// Generated by arsxml2wv from node 4 (이체 확인). Review before use.
var sWorkTime = app.worktime;
var sWTType = "B";
if (sWorkTime == "Y")
{
	sWTType = "A";
}

var wvMsgType = "WV2000Q";
var wvMenu = "";

wvMenu += "S\$SHKD12;";
wvMenu += "BTH\$0\$OFF;";
wvMenu += "BTH\$1\$ON;";
wvMenu += "TIT\$0\$테스트 이체;";
wvMenu += "TXT\$0\$C\$원하시는 메뉴를 선택해 주세요.;";
wvMenu += "BTN\$0\$이체를 진행\$1;";
wvMenu += "BTN\$1\$취소\$2;";
wvMenu += "BTN\$2\$초기메뉴 이동\$#;";
wvMenu += "CHA\$0\$" + app.wvChat + ";";
wvMenu += "BOT\$0\$" + sWTType + ";";

app.wvMsgType = wvMsgType;
app.wvMenu = wvMenu;
app.wvReadTimeout = "B";
app.wvMaxRetryCount = "2";	// 최대 화면 팝업 횟수
